@baseUrl = http://localhost:8080/api
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzMxMjA1MjIsInN1YiI6ImFkY2M2OGExLWIyNzAtNDY5MS04ZGQxLTY2Y2I3N2ZlZDQ0YiJ9.xwXezT3P9PNQojRGmFf4sLE0mEWkDxF8Jvwmdt3Afgw
@name = "new-user"
@email = "newuser@email.com"
@password = "root"
@userToFollow = yeah

### Create a new user
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
  "user":{
    "username": {{name}},
    "email": {{email}},
    "password": "root"
  }
}

### Login to receive the token
POST {{baseUrl}}/users/login HTTP/1.1
Content-Type: application/json

{
  "user":{
    "email": {{email}},
    "password": {{password}}
  }
}

### Get All Users
GET {{baseUrl}}/user/all
Content-Type: application/json
Authorization: {{token}}

### Get Current User
GET {{baseUrl}}/user HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

### Edit an user
PUT {{baseUrl}}/user HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "user":{
    "email": {{email}},
    "username": "danilo"
  }
}

###
GET {{baseUrl}}/profiles/{{userToFollow}}
Authorization: {{token}}

### Follow a user
POST {{baseUrl}}/profiles/{{userToFollow}}/follow
Authorization: {{token}}

### UNfollow a user
DELETE {{baseUrl}}/profiles/{{userToFollow}}/follow
Authorization: {{token}}
