@baseUrl = http://localhost:8080/api
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjY3ODEyOTAsInN1YiI6ImZiYmRjZDIxLWFlZmMtNGQxNC1hMmM1LTFhZjc5ZDg1ZTliYyJ9.m84bbEAwZNjwI8W_yE7bolU4-EbZyxEqj8LWYFkDmwU
@name = "oliveira"
@email = "oliveira@email.com"
@password = "root"

### Create a new user
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
  "user":{
    "username": {{name}},
    "email": {{email}},
    "password": "root"
  }
}

### Login to receive the token
POST {{baseUrl}}/users/login HTTP/1.1
Content-Type: application/json

{
  "user":{
    "email": {{email}},
    "password": {{password}}
  }
}

### Get All Users
GET {{baseUrl}}/user/all
Content-Type: application/json
Authorization: {{token}}

### Get Current User
GET {{baseUrl}}/user HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

### Edit an user
PUT {{baseUrl}}/user HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "user":{
    "email": {{email}},
    "username": "yeah"
  }
}

###
GET {{baseUrl}}/profiles/karol
Authorization: {{token}}